return {
    {
      "folke/snacks.nvim",
      priority = 1000,
      lazy = false,
      ---@type snacks.Config
      opts = {
        animate = { enabled = false },
        bigfile = { enabled = true },
        bufdelete = { enabled = true },
        dashboard = { enabled = false },
        debug = { enabled = false },
        dim = { enabled = false },
        explorer = { enabled = false },
        git = { enabled = false },
        gitbrowse = { enabled = false },
        image = { enabled = false },
        indent = { enabled = false },
        input = { enabled = false },
        layout = { enabled = false },
        lazygit = { enabled = true },
        picker = { enabled = false },
        notifier = { enabled = false },
        profiler = { enabled = false },
        quickfile = { enabled = true },
        rename = { enabled = false },
        scope = { enabled = false },
        scroll = { enabled = true },
        scratch = { enabled = false },
        statuscolumn = { enabled = false },
        terminal = { enabled = false },
        toggle = { enabled = false },
        util = { enabled = false },
        win = { enabled = false },
        words = { enabled = true },
        zen = { enabled = true },
      }
    },
}
